import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/favicoan.ico'
  }
};

const font = Inter({
  subsets: ['latin'],
  weight:['400', '700']
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={font.className}>
      <body className="bg-secondary-background">
        {children}
      </body>
    </html>
  );
}
